alias hm=home-manager
alias ble="brew list --installed-on-request"
alias exal="eza -bghHliS"
alias ezal="eza -bghHliS"
alias cat="bat"
alias exaa="eza -abghHliS"
alias ezaa="eza -abghHliS"
alias nv="nvim"
alias chezig="nvim ~/.local/share/chezmoi/.chezmoiignore"
