require("options")
require("plugins")
require("configs/coc_options")
require("configs/telescope")
require("configs/comment")
-- require("configs/coc_nvim-notify")
require("configs/nvim-tree")
require("configs/vim-airline")
require("configs/tagbar")
require("configs/quickr-cscope")
require("configs/barbar")

